[package]
name = "fitgirl-ddl-gui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fitgirl-ddl_gui"
path = "src/main.rs"


[dependencies]
fitgirl-ddl-lib = { workspace = true }
nyquest-preset = { workspace = true }
compio = { workspace = true, features = ["time"] }
futures-util = { workspace = true }
itertools = { workspace = true }
spdlog-rs = { workspace = true }

winio = { git = "https://github.com/compio-rs/winio", default-features = false, version = "0.7.0-beta.2" }
ahash = "0.8.12"

serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"

[features]
default = ["gtk", "dark-mode"]
gtk = ["winio/gtk"]
qt = ["winio/qt"]

dark-mode = ["winio/windows-dark-mode"]
