[package]
name = "fitgirl-ddl-gui"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "fitgirl-ddl_gui"
path = "src/main.rs"

[dependencies]
fitgirl-ddl-lib = { workspace = true }
nyquest-preset = { workspace = true }
compio = { workspace = true, features = ["time"] }
futures-util = { workspace = true }
itertools = { workspace = true }
spdlog-rs = { workspace = true }

winio = { git = "https://github.com/compio-rs/winio", default-features = false }
ahash = "0.8.12"

[features]
default = ["gtk"]
gtk = ["winio/gtk"]
qt = ["winio/qt"]
