name: publish-release

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  windows-10:
    uses: ./.github/workflows/windows-10.yaml

  windows-11:
    uses: ./.github/workflows/windows-11.yaml

  macos:
    uses: ./.github/workflows/macos.yaml

  linux-glibc:
    uses: ./.github/workflows/linux-glibc.yaml

  release:
    needs:
      - windows-10
      - windows-11
      - macos
      - linux-glibc

    runs-on: ubuntu-24.04

    steps:
      - uses: actions/download-artifact@v8
        with:
          path: artifacts

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/**/*
          prerelease: false
