name: build-windows-11

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - artifact: win11-x86_64.exe
            runner: windows-2022
            target: x86_64-pc-windows-msvc

          - artifact: win11-arm64.exe
            runner: windows-11-arm
            target: aarch64-pc-windows-msvc

    name: ${{ matrix.artifact }}

    steps:
      - uses: actions/checkout@v6

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2026-07-02
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: ${{ matrix.artifact }}

      - name: Install NASM
        if: contains(matrix.target, 'x86_64')
        shell: pwsh
        run: |
          choco install nasm -y --no-progress
          "C:\Program Files\NASM" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        shell: bash
        run: |
          cargo build \
            --release \
            --target ${{ matrix.target }}

      - name: Collect
        shell: bash
        run: |
          mkdir dist
          for bin in fitgirl-ddl fitgirl-ddl_gui; do
            cp "target/${{ matrix.target }}/release/${bin}.exe" "dist/${bin}-${{ matrix.artifact }}"
          done

      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.artifact }}
          path: dist/*
